### ISSUE TITLE
[Admin - Desktop] My business entities: Contact Details fields are mandatory

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#158]
**Environment:** Windows 10/ Chrome 83

**Note:** Ticket is related to #41 ticket

**Steps:**

1. Log in to Admin Demo site
2. Click on My business entities tab
3. Click New Business Unit button
4. Pay attention to Contact Person Details field

**Actual result:** Contact Details fields are mandatory
**Expected result:** Contact Details fields are non-mandatory
![image.png](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/ed8f1c93-7a76-4a3e-9fe1-c33afb6f5fe6)

**Comment by MarlonMaercz** [comment]
@MarlonMaercz @ElenaBelyavskaya Check behavior to see if all fields need to be mandatory.

**Comment by vitaliidasaev** [comment]
For now backend requires:
If any of the fields filled (First Name or Last Name or Phone or Email)
then it requires all others to be filled.

I expected that all fields are optional and can be filled separately.

**Comment by ElenaBelyavskaya** [comment]
We earlier agreed and implemented that these fields should be optional: https://github.com/openmavn/mavn.service.partnermanagement/issues/50

**Comment by vitaliidasaev** [comment]
@IliyanIlievPH because every fields should be optional - 
please remove validations for all fields to be filled  
https://github.com/OpenMAVN/MAVN.Service.PartnerManagement/pull/51/files#diff-b31b3e91b6e4e0f4b8bafba77151ce74R16
and in admin-api https://github.com/OpenMAVN/MAVN.Service.AdminAPI/pull/63/files#diff-14c46ed1a7e3100265ca306f681b6179R35
