### ISSUE TITLE
Set up email service to send out messages

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#45]
**Current Behavior:**
OpenMAVN is currently only using a mocked service to send emails.

**Required Behavior:**
A proper service is needed to send out emails (e.g. email verification, notification emails, newsletters, etc.) to customers and SME's.

The proposed service is SendGrid due to it's known compatibility with our system. 

**Acceptance Criteria**
1. Email service is set up and can be used by OpenMAVN
2. Users should be able to receive emails when registering using the mobile app.

**Comment by MarlonMaercz** [comment]
@thelittledevops can you please add some required details about what is required to get email service up and running?

**Comment by thelittledevops** [comment]
sendgrid emails service is supported by azure, but there are two ways of it's setup:
1. using the free or cheap tier, which has the shared ip address , which is also used by other companies, often to send advertisements and etc  and that's why our emails will get spammed
2. using the dedicated ip address , that way we can guarantee that our source ip address will not have reputation , but it will cost us 79$ a month
